version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Build completed on `date`
      - "echo Listing contents of target directory:"
      - ls -la target/

  post_build:
    commands:
      - echo Post-build started on `date`
      - |
        JAR_FILE=$(ls target/*.jar 2>/dev/null | head -n 1)
        if [ -z "$JAR_FILE" ]; then
          echo "ERROR: No JAR found in target/"
          exit 1
        fi
        echo "Uploading $JAR_FILE to S3..."
        aws s3 cp "$JAR_FILE" s3://myfilescloud/
        echo JAR uploaded to S3 successfully

artifacts:
  files:
    - target/*.jar
