version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21   # or corretto11 if you use Java 11
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Build completed successfully
      # copy JAR to S3
      - aws s3 cp target/*.jar s3://your-artifacts-bucket-myfilescloud/
      - echo JAR uploaded to S3

artifacts:
  files:
    - target/*.jar
