version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
  base-directory: target
