version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Build completed on `date`
      - echo Listing contents of target directory:
      - ls -la target/

  post_build:
    commands:
      - echo Post-build started on `date`
      # Get the final JAR name from Maven
      - JAR_FILE=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout).jar
      - if [ ! -f "target/$JAR_FILE" ]; then echo "ERROR: JAR not found in target/"; exit 1; fi
      - echo "Uploading target/$JAR_FILE to S3..."
      - aws s3 cp "target/$JAR_FILE" s3://myfilescloud/
      - echo JAR uploaded to S3 successfully

artifacts:
  files:
    - target/*.jar
